excluded:
  - Pods
  - WoWDatabase/Resources/Generated

disabled_rules:
  - trailing_whitespace
  - line_length
  - nesting
  - type_name
  - identifier_name
  - cyclomatic_complexity
  - large_tuple
